image: Visual Studio 2019

build_script:
  - Get-Location
  - Start-FileDownload 'https://static.kvraudio.com/files/3148/orilriver_win203.zip'
  - Expand-Archive -LiteralPath orilriver_win203.zip
  - dir
  - dotnet restore

after_build:
  - Get-Location
  - dir
  - dotnet test
