image: Visual Studio 2019

build_script:
  - ps: Get-Location
  - ps: Start-FileDownload 'https://nktkz.s3.eu-central-1.amazonaws.com/development/github/VSTAudioProcessor/orilriver_win203.zip'
  - ps: Expand-Archive -LiteralPath orilriver_win203.zip

after_build:
#  - dir orilriver_win203
  - msbuild VSTAudioProcessor.Test
  - xunit.console.clr4 ./VSTAudioProcessor.Test/bin/Debug/VSTAudioProcessor.Test.dll /appveyor
